### ISSUE TITLE
When i finaly got it to work it only syncs 1 or two eps at the time?

### ISSUE THREAD

**Issue by basn** [Beaujr/plex2emby#1]
Is there any specific parameters etc to be set?
or is it to rerun the program over and over?

/go/src/github.com/beaujr/plex2emby# go run main.go
22 Jump Street,22 Jump Street,watched
2,The 100,Season 1,1,Watched
2,The 100,Season 1,2,Watched
2,The 100,Season 1,3,Watched
2,The 100,Season 1,4,Watched
2,The 100,Season 1,5,Watched
2,The 100,Season 1,6,Watched
2,The 100,Season 1,7,Watched
2,The 100,Season 1,8,Watched
2,The 100,Season 1,9,Watched
2,The 100,Season 1,10,Watched
2,The 100,Season 1,11,Watched

etc (it gives 1 watched per run)

**Comment by Beaujr** [comment]
Hi @basn, I wrote this V Quick, thanks for the feedback. I just ran it once and then decommissioned my plex instance. If you are thinking of keeping Plex & Emby in sync, I'd suggest using something like track.tv plugins for plex and emby

**Comment by Beaujr** [comment]
Plex
https://github.com/trakt/Plex-Trakt-Scrobbler

Emby
https://emby.media/community/index.php?/topic/35269-trakt-sync-from-trakt-to-emby/


Trakt
https://trakt.tv/

**Comment by basn** [comment]
nah, i am switching hopefully.
but it only syncs 1 thing per run.. thats what i tried to say, so id have to run it several hundred times then :)

**Comment by Beaujr** [comment]
@basn weird, for myself it syncs my whole library per run. Are you familiar with Docker?
I can push an image and get you to test?

**Comment by Beaujr** [comment]
Please try
```
docker run --net=host \
-e embyURL="<EMBY URL>" \
-e embyAPIKEY="<EMBY API KEY>" \
-e embyUSERKEY="<EMBY USER KEY>" \
-e plexURL="<PLEX URL>" \
-e plexAPIKEY="<PLEX API KEY>" \
docker.com/beaujr/plex2emby:0.1
```

**Comment by basn** [comment]
Docker is fine, but i cant get that repo to work, i get 404.

**Comment by Beaujr** [comment]
Sorry I've amended it, please try again. I removed the docker.com/ part of the image reference

**Comment by basn** [comment]
Yeah just found it on dockerhub, trying :)

**Comment by basn** [comment]
same there, for everytime i run it i get 1 more flagged ep and then it shuts off.

**Comment by basn** [comment]
maybe its a jellyfin issue, i am going to try original emby...

**Comment by basn** [comment]
nah, same with emby abit more but still 1 ep at the time. :(
i really dislike using trakt but i guess i have to go that way

**Comment by Beaujr** [comment]
I'm really sorry @basn all I can think of is trailing slashes on server names. Can you try removing any trailing slashes on the plexURL and embyURL Env params

**Comment by basn** [comment]
docker run --net=host -e embyURL="https://emby.xxx.xx" -e embyAPIKEY="embykey" -e embyUSERKEY="embyuserkey" -e plexURL="https://plex.xxx.xx" -e plexAPIKEY="plexkey" beaujr/plex2emby:0.1

**Comment by basn** [comment]
not working :/

**Comment by Beaujr** [comment]
@basn, sorry for the delay but I actually found a reason for your issue. Jellyfin was forked at a lower version level of Emby than I was using. As such the API was slightly different causing the issue you had. I recently updated it in my working copy to work against Jellyfin 10.0.1.0. If you still require this let me know and I'll PR it in :)

**Comment by basn** [comment]
Damn awesome, i will try it later :)

**Comment by Beaujr** [comment]
What issue are you using atm? 10.0.1.0?

**Comment by basn** [comment]
sorry, no issues so far.. haven't had time to check it yet..
ill update when i know how it works.
